### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by alabd14313** [TReed0803/OpenSK#1]
Hello @TReed0803 !
I have two questions:
1) OpenSK is under which license (why MIT and not LGPL)?
2) Is OpenSK appropriate for game engines, or need a higher wrapper?

**Comment by timofonic** [comment]
I have other questions, excuse me to spam this issue:

Does this project has some kind of a Microsoft endorsement? 

Why OpenSK instead OpenAL or SDL2? (And ya, I'm interested about higher level APIs/wrappers and OpenSK). 

What about Input-Output functions covered by APIs like SDL2 and Allegro (I know it's mostly abandoned, but it's another example)? 

To me, Vulkan/OpenGL lack a full APIs/wrappers set like DirectX that could be available in a multiplatform way. Khronos Group has some unrelated APIs, but mostly targeted at embedded world and lack any kind of cohesion. 

Any hopes to have a multiplatform and platform agnostic equivalent to DirectX (or even a lot better if possible)?

**Comment by TReed0803** [comment]
Currently OpenSK is MIT licensed, I don't want to be restrictive with my licensing so I wasn't particularly interested in GPL-based licenses. The license might change at a later date, the only thing I really want is attribution to the OpenSK project should it be used in a product or service, so perhaps I'll drop the LICENSE file until I figure this out for sure.

OpenSK is very low level, in order to use it happily you might want to have a wrapper library which acts as the audio engine for your game. I saw the need for a more low-level sound API, but I wanted access to more than just the PCM streams - I didn't see anything like this so I started rolling my own.

**_There is absolutely no Microsoft endorsement behind this project_**, I'm just a passionate developer working hard to make the tools and APIs that I need (and think other developers may want).

OpenAL and SDL2 is a little higher-level than what I want to accomplish with OpenSK, I really want to give the developer access to the raw materials here and nothing more.

Right now, API support is limited - I'm doing the design and legwork on Linux with ALSA sound drivers. After I finalize what I want a little more I'm going to start pulling in other platform's APIs. In the end, I hope to support at least the big three (Linux, OSX, Windows). **Until I've announced beta, I wouldn't take any hard dependency on the API.** Though I'm always looking for people to test what's there, so feel free to play around as much as you want - I just wouldn't ship a product with it, and be aware it's under constant development and API changes right now.

After I get a little further in development I hope to create a PPA for Ubuntu LTS so that people can apt-get the libraries and utilities to make this kind of development work and testing easier (hopefully when the API is locked down a little better). So look forward to that in a few months if you want to play with OpenSK but don't want to have the hassle of building the binaries. 

I think OpenSK can be summarized up nicely as such:
OpenGL is to OpenAL, what Vulkan is to OpenSK.
You can see this in the design itself, being very similar in format and philosophy to Vulkan.

I take the opposite stance and see Vulkan and OpenGL as being very prominent APIs which lend themselves nicely to either a full modern C++ development pipeline, or a clean C embedded pipeline - not to mention it's pretty easy to bind C to other languages. If you want the cleanliness and high-level accessibility of DirectX but with OpenGL, you'd write (or use) a wrapper - the operations the SDKs perform are relatively similar. Likewise, I would expect that higher-level wrapper SDKs would pop-up for SDKs like Vulkan and OpenSK.

The plan right now is to get OpenSK working well-enough to call beta. I think this will take quite a few months, if not maybe a year or so. After that, I will likely begin working on a higher-level wrapper like you're talking about, but it's not going to be standard to OpenSK, it'll be it's own audio engine that uses OpenSK as a base library.

**The key takeaways:**
1. OpenSK is MIT-licensed, and the only future addendum I have planned is to require attribution if OpenSK is used in a product or service.
2. Yes, OpenSK should be fine for game engines, but may be a bit too low-level.
3. This project is currently being developed by a sole developer, and is not endorsed by anyone at the moment.
4. The difference between OpenSK and SDL2, OpenAL, PortAudio, etc.? Key design philosophies.
5. I don't recommend taking a dependency on OpenSK until beta is announced, and I don't expect beta to be announced for at least 6 months to a year.

Please let me know if this answers your questions appropriately - I'd love feedback on the API or design philosophies of the OpenSK project if you have time. I'd also like to know what brought you to this project and why each of you wants to use this API? It helps to know your prospective audience. :)

**Comment by TReed0803** [comment]
Closing this out since I haven't heard back - Please feel free to email me if you have further questions.
